FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /code
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . .
CMD sh -c "sleep 5 && \
           python manage.py migrate && \
           python manage.py runserver 0.0.0.0:8014"
...
CMD gunicorn medical_records_service.wsgi:application --bind 0.0.0.0:8014
